### ISSUE TITLE
Please add a Jammy Jellyfish repo

### ISSUE THREAD

**Issue by Kiendeleo** [qmk/qmk_fpm#13]
### Description

Please add a repo for the 22.04 of Ubuntu

**Comment by YamiYukiSenpai** [comment]
Or if you're planning to support non-LTS, please add Lunar and Mantic, too

**Comment by tzarc** [comment]
There's a PR open that had support for Jammy, can probably adapt it for the others.
When and if it gets merged is another thing entirely.

**Comment by tzarc** [comment]
Done. Ubuntu Lunar added. When the newest Ubuntu is released I'll look at adding a target.
