### ISSUE TITLE
[Bug] Readme.md dead link for "All Debian-like distributions"

### ISSUE THREAD

**Issue by QuartzMovement** [qmk/qmk_fpm#9]
### Describe the Bug

The Readme.md file says to "follow the instructions under [All Debian-like distributions](https://github.com/qmk/qmk_fpm/blob/main/all-debian-like-distributions)."
That link leads to https://github.com/qmk/qmk_fpm/blob/main/all-debian-like-distributions, which gives a 404 error.

### Additional Context?

![image](https://user-images.githubusercontent.com/33850146/174491437-c5b67989-0a94-46b2-bed3-3ba595a2fdc2.png)

**Comment by Kiendeleo** [comment]
Bumping this it is still linked to a dead URL

**Comment by tzarc** [comment]
Should be irrelevant, now. Refactored the readme.
